
import { Urbanist } from '@next/font/google';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const urbanist = Urbanist({
  weights: [400, 500, 700],
  subsets: ['latin'],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={urbanist.className}>{children}</body>
    </html>
  )
}
